#!/bin/sh
set -eu

if [ -f .env ]; then
  echo ".env already exists; leaving it unchanged."
  exit 0
fi

prompt() {
  name="$1"
  default="$2"
  description="$3"

  printf "%s\n" "$description"
  if [ -n "$default" ]; then
    printf "%s [%s]: " "$name" "$default"
  else
    printf "%s: " "$name"
  fi

  term="${TERM:-dumb}"
  if [ "$term" = "dumb" ] || [ ! -t 0 ]; then
    answer="$default"
  else
    read answer
  fi

  if [ -z "$answer" ]; then
    answer="$default"
  fi
  printf '%s=%s\n' "$name" "$answer"
}

secret() {
  python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(48))
PY
}

AGENT_TOKEN_LINE="AGENT_TOKEN=$(secret)"
SECRET_KEY_LINE="SECRET_KEY=$(secret)"
BASE_URL_LINE="$(prompt "BASE_URL" "http://localhost:8080" "Public URL for this ScriptWatch instance")"
ADMIN_USERNAME_LINE="$(prompt "ADMIN_USERNAME" "admin" "Administrator username")"
ADMIN_PASSWORD_LINE="$(prompt "ADMIN_PASSWORD" "" "Administrator password (leave blank to set in UI)")"
ADMIN_TOKEN_LINE="$(prompt "ADMIN_TOKEN" "" "Optional admin API token")"
NTFY_URL_LINE="$(prompt "NTFY_URL" "" "Optional ntfy endpoint URL")"
NTFY_TOKEN_LINE="$(prompt "NTFY_TOKEN" "" "Optional ntfy token")"
DISCORD_WEBHOOK_URL_LINE="$(prompt "DISCORD_WEBHOOK_URL" "" "Optional Discord webhook URL")"
MISSED_RUN_GRACE_MINUTES_LINE="$(prompt "MISSED_RUN_GRACE_MINUTES" "15" "Missed run grace period in minutes")"
JOB_RETENTION_DAYS_LINE="$(prompt "JOB_RETENTION_DAYS" "30" "Completed job retention in days")"

cat > .env <<EOF
# ScriptWatch Standalone environment
# Generated by tools/setup-env.sh

DATABASE_URL=sqlite:////app/data/scriptwatch.db
DATA_DIR=/app/data
SCRIPT_STORE_DIR=/app/data/script-store

$AGENT_TOKEN_LINE
$SECRET_KEY_LINE

$BASE_URL_LINE
$ADMIN_USERNAME_LINE
$ADMIN_PASSWORD_LINE
$ADMIN_TOKEN_LINE
$NTFY_URL_LINE
$NTFY_TOKEN_LINE
$DISCORD_WEBHOOK_URL_LINE
$MISSED_RUN_GRACE_MINUTES_LINE
$JOB_RETENTION_DAYS_LINE
EOF

echo "Created .env. Review it before starting the app."
